---
apiVersion: v1
kind: SecurityContextConstraints
metadata:
    name: uid1001
requiredDropCapabilities:
- KILL
- MKNOD
- SYS_CHROOT
- SETUID
- SETGID
runAsUser:
    type: MustRunAs
    uid: 1001
seLinuxContext:
    type: MustRunAs
supplementalGroups:
    type: RunAsAny
fsGroup:
    type: MustRunAs
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret